KNN Imputation

In [ ]:
import numpy as np

import pandas as pd

from sklearn.impute import KNNImputer

df = pd.read_csv("outliers_imputation_practice.xls")

imputer = KNNImputer(n_neighbors = 2)

df_imputed = pd.DataFrame(
    imputer.fit_transform(df),
    columns = df.columns
)

print("After KNN imputation:")
df_imputed.head()

MICE Imputaion

In [ ]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

df = pd.read_csv("outliers_imputation_practice.xls")

imputer = IterativeImputer(
    max_iter = 10,
    random_state = 42
)

df_imputed = pd.DataFrame(
    imputer.fit_transform(df),
    columns = df.columns
)

df_imputed.head()

Simple Imputation (Mean,Median,Mode)

In [ ]:
from sklearn.impute import SimpleImputer

df_mean = df.copy()

imputer = SimpleImputer(strategy="mean")

df_mean[["income"]] = imputer.fit_transform(df_mean[["income"]])

df_mean.head(10)

Z - Score Detection

In [ ]:
import numpy as np

from scipy.stats import zscore

data = np.array([10, 12, 11, 13, 12, 14, 100])

z_score = zscore(data)

outliers = data[np.abs(z_score) > 2]

print(outliers)

IQR method

In [ ]:
import numpy as np

data = np.array([10, 12, 11, 13, 12, 14, 100])

Q1 = np.percentile(data, 25)
Q3 = np.percentile(data, 75)
IQR = Q3 - Q1

lower_bond = Q1 - 1.5 * IQR
upper_bond = Q3 + 1.5 * IQR

outlier = data[(data < lower_bond) | (data > upper_bond)]

print(outlier)

In [ ]:
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

Q1 = df["income"].quantile(0.25)
Q3 = df["income"].quantile(0.75)

IQR = Q3 - Q1

lower_bond = Q1 - 1.5 * IQR
upper_bond = Q3 + 1.5 * IQR

outliers = df[
    (df["income"] < lower_bond) | (df["income"] > upper_bond)
]

print(outliers)

Remove outliers using IQR

In [ ]:
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

Q1 = df["income"].quantile(0.25)
Q3 = df["income"].quantile(0.75)

IQR = Q3 - Q1

lower_bond = Q1 - 1.5 * IQR
upper_bond = Q3 + 1.5 * IQR

df_clean = df[
    (df["income"] >= lower_bond) & (df["income"] <= upper_bond)
]

print(df_clean)

Log Transformation for Outliers

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("outliers_imputation_practice.xls")

df["log_income"] = np.log1p(df["income"])

df[["income", "log_income"]].head(10)

Square-Root Transformation

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

df["income_sqrt"] = np.sqrt(df["income"])

df[["income", "income_sqrt"]].head(10)

Capping and Flooring

In [7]:
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

Q1 = df["income"].quantile(0.25)
Q3 = df["income"].quantile(0.75)

IQR = Q3 - Q1

lower_bond = Q1 - 1.5 * IQR
upper_bond = Q3 + 1.5 * IQR

df["capped_income"] = df["income"].clip(
    lower=lower_bond,
    upper=upper_bond
)

df["capped_income"].head()

0    192108.58
1    115700.97
2    118094.75
3    207761.74
4     53154.85
Name: capped_income, dtype: float64

Min-Max Normalization

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

scaler = MinMaxScaler()

df_scaled = df.copy()

df_scaled = pd.DataFrame(
    scaler.fit_transform(df),
    columns=df.columns
    )

df_scaled.head()

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction
0,0.904762,0.850,0.75,0.202808,0.130008,1.000000,0.180124,0.601100
1,0.666667,0.475,0.25,0.114234,0.120964,0.922613,0.105590,NaN
2,0.333333,0.350,0.75,0.117009,0.185403,0.884827,0.080745,0.658872
3,1.000000,0.925,0.50,0.220954,0.314280,1.000000,NaN,0.382393
4,0.166667,NaN,0.75,0.041729,0.111920,NaN,0.000000,1.000000

Standardization (Z-score Scaling)

In [19]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("outliers_imputation_practice.xls")

scaler = StandardScaler()

df_std = df.copy()

df_std = pd.DataFrame(
    scaler.fit_transform(df),
    columns=df.columns
    )

df_std.mean()

age                   3.113203e-17
experience_years      2.991759e-17
education_years       3.645232e-16
income               -2.447425e-16
hours_per_week        7.143222e-16
performance_score    -6.171924e-17
projects_completed    5.730183e-17
job_satisfaction     -3.035423e-16
dtype: float64

Robust Scaling

In [20]:
import pandas as pd
from sklearn.preprocessing import RobustScaler

df = pd.read_csv("outliers_imputation_practice.xls")

scaler = RobustScaler()

df_scaled = pd.DataFrame(
    scaler.fit_transform(df),
    columns=df.columns
    )

df_scaled.head()

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction
0,0.727273,0.809524,0.0,0.745157,-0.919192,0.381437,0.8125,0.163823
1,0.272727,0.095238,-2.0,-0.065218,-1.000000,0.063417,0.0625,NaN
2,-0.363636,-0.142857,0.0,-0.039830,-0.424242,-0.091862,-0.1875,0.354949
3,0.909091,0.952381,-1.0,0.911174,0.727273,0.381437,NaN,-0.559727
4,-0.681818,NaN,0.0,-0.728580,-1.080808,NaN,-1.0000,1.483504

Feature Engineering

In [21]:
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

df["career_start"] = (df["age"] - df["experience_years"])

df.head()

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction,career_start
0,56.0,34.0,16.0,192108.58,33.0,100.00,29.0,7.10,22.0
1,46.0,19.0,12.0,115700.97,32.2,93.18,17.0,NaN,27.0
2,32.0,14.0,16.0,118094.75,37.9,89.85,13.0,7.52,18.0
3,60.0,37.0,14.0,207761.74,49.3,100.00,NaN,5.51,23.0
4,25.0,NaN,16.0,53154.85,31.4,NaN,0.0,10.00,NaN

Combining Features

In [22]:
import pandas as pd

df["overall_score"] = (df["performance_score"] + df["job_satisfaction"]) / 2

df.head()

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction,career_start,overall_score
0,56.0,34.0,16.0,192108.58,33.0,100.00,29.0,7.10,22.0,53.550
1,46.0,19.0,12.0,115700.97,32.2,93.18,17.0,NaN,27.0,NaN
2,32.0,14.0,16.0,118094.75,37.9,89.85,13.0,7.52,18.0,48.685
3,60.0,37.0,14.0,207761.74,49.3,100.00,NaN,5.51,23.0,52.755
4,25.0,NaN,16.0,53154.85,31.4,NaN,0.0,10.00,NaN,NaN

Log Transformation

In [25]:
import pandas as pd
import numpy as np

df = pd.read_csv("outliers_imputation_practice.xls")

df["income_log"] = np.log1p(df["income"])

df.head(10)

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction,income_log
0,56.0,34.0,16.0,192108.58,33.0,100.00,29.0,7.10,12.165821
1,46.0,19.0,12.0,115700.97,32.2,93.18,17.0,NaN,11.658773
2,32.0,14.0,16.0,118094.75,37.9,89.85,13.0,7.52,11.679251
3,60.0,37.0,14.0,207761.74,49.3,100.00,NaN,5.51,12.244152
4,25.0,NaN,16.0,53154.85,31.4,NaN,0.0,10.00,10.880983
5,38.0,17.0,12.0,96061.38,22.2,96.75,20.0,7.09,11.472753
6,56.0,31.0,16.0,192654.18,38.8,100.00,27.0,6.58,12.168657
7,36.0,15.0,16.0,101907.42,45.9,NaN,15.0,8.25,11.531830
8,40.0,15.0,12.0,107699.33,50.4,100.00,14.0,7.17,11.587108
9,28.0,3.0,12.0,55873.77,38.8,54.52,3.0,7.40,10.930868

Polynomial Features

In [ ]:
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.impute import KNNImputer

df = pd.read_csv("outliers_imputation_practice.xls")

#PolynomialFeatures can't be used while missing values are present
imputer = KNNImputer(n_neighbors=3)

x = df[["experience_years"]]

df_imputed = pd.DataFrame(
    imputer.fit_transform(x),
    columns=["experience_years"]
)

poly = PolynomialFeatures(
    degree=2,
    include_bias=False
)

df_poly = pd.DataFrame(
    poly.fit_transform(df_imputed),
    columns=["experience_years", "experience_years^2"]
)

df_poly.head(10)

   experience_years  experience_years^2
0         34.000000         1156.000000
1         19.000000          361.000000
2         14.000000          196.000000
3         37.000000         1369.000000
4         16.869474          284.579142
5         17.000000          289.000000
6         31.000000          961.000000
7         15.000000          225.000000
8         15.000000          225.000000
9          3.000000            9.000000

One-Hot Encoding

In [ ]:
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

#There is no categories in the data set so did this
df["experience_level"] = pd.cut(
    df["experience_years"],
    bins=[0, 5, 15, 100],
    labels=["Junior", "Mid", "Senior"]
)

#This is the part of One-Hot Encoding
df_enoded = pd.get_dummies(
    df,
    columns=["experience_level"],
    dtype=int
)

df_enoded.head()

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction,experience_level_Junior,experience_level_Mid,experience_level_Senior
0,56.0,34.0,16.0,192108.58,33.0,100.00,29.0,7.10,0,0,1
1,46.0,19.0,12.0,115700.97,32.2,93.18,17.0,NaN,0,0,1
2,32.0,14.0,16.0,118094.75,37.9,89.85,13.0,7.52,0,1,0
3,60.0,37.0,14.0,207761.74,49.3,100.00,NaN,5.51,0,0,1
4,25.0,NaN,16.0,53154.85,31.4,NaN,0.0,10.00,0,0,0

Label Encoding

In [42]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("outliers_imputation_practice.xls")

#There is no categories in the data set so did this
df["experience_level"] = pd.cut(
    df["experience_years"],
    bins=[0, 5, 15, 100],
    labels=["Junior", "Mid", "Senior"]
)

encode = LabelEncoder()

df["experience"] = encode.fit_transform(df["experience_level"])

df.head()

    age  experience_years  ...  experience_level  experience
0  56.0              34.0  ...            Senior           2
1  46.0              19.0  ...            Senior           2
2  32.0              14.0  ...               Mid           1
3  60.0              37.0  ...            Senior           2
4  25.0               NaN  ...               NaN           3

[5 rows x 10 columns]

Correlation Practical

In [7]:
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

correlation = df.corr(numeric_only=True)

display(correlation)

                         age  ...  job_satisfaction
age                 1.000000  ...         -0.037613
experience_years    0.971990  ...         -0.053385
education_years     0.070049  ...         -0.004700
income              0.777266  ...         -0.040896
hours_per_week     -0.012017  ...         -0.011210
performance_score   0.680879  ...         -0.039823
projects_completed  0.844886  ...         -0.087502
job_satisfaction   -0.037613  ...          1.000000

[8 rows x 8 columns]

Correlation With a Target

In [8]:
correlation = (df.corr(numeric_only=True)["age"].sort_values(ascending=False))

print(correlation)

age                   1.000000
experience_years      0.971990
projects_completed    0.844886
income                0.777266
performance_score     0.680879
education_years       0.070049
hours_per_week       -0.012017
job_satisfaction     -0.037613
Name: age, dtype: float64

Variance Threshold

In [13]:
from sklearn.feature_selection import VarianceThreshold
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

selector = VarianceThreshold(threshold=3)

selected_columns = pd.DataFrame(
    selector.fit_transform(df),
    columns=df.columns[selector.get_support()]
    )

display(selected_columns)

      age  experience_years  ...  performance_score  projects_completed
0    56.0              34.0  ...             100.00                29.0
1    46.0              19.0  ...              93.18                17.0
2    32.0              14.0  ...              89.85                13.0
3    60.0              37.0  ...             100.00                 NaN
4    25.0               NaN  ...                NaN                 0.0
..    ...               ...  ...                ...                 ...
995  50.0              31.0  ...             100.00                24.0
996  21.0               0.0  ...              59.19                 4.0
997  39.0               NaN  ...              89.10                16.0
998  19.0               0.0  ...              90.18                 2.0
999  27.0               3.0  ...                NaN                 5.0

[1000 rows x 7 columns]

Recursive Feature Elimination

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

X = df.drop(columns=["income"])
y = df["income"]

X = X.fillna(X.median())
y = y.fillna(y.median())

model = LinearRegression()

rfe = RFE(estimator=model, n_features_to_select=3)

rfe.fit(X, y)

selected_feature = X.columns[rfe.support_]

print(selected_feature)

Index(['age', 'experience_years', 'education_years'], dtype='str')

Lasso Practical

In [ ]:
from sklearn.linear_model import Lasso
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

X = df.drop(columns=["income"])
y = df["income"]

X = X.fillna(X.median())
y = y.fillna(y.median())

lasso = Lasso(alpha=0.1)

lasso.fit(X, y)

coefficient = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": lasso.coef_
})

display(coefficient)

selected_feature = coefficient[coefficient["Coefficient"] != 0]

display(selected_feature)

              Feature  Coefficient
0                 age  1130.880480
1    experience_years  2824.859408
2     education_years  1089.440599
3      hours_per_week   -35.370405
4   performance_score   114.928044
5  projects_completed   256.685942
6    job_satisfaction   -37.668392

              Feature  Coefficient
0                 age  1130.880480
1    experience_years  2824.859408
2     education_years  1089.440599
3      hours_per_week   -35.370405
4   performance_score   114.928044
5  projects_completed   256.685942
6    job_satisfaction   -37.668392

Ridge Practical

In [41]:
from sklearn.linear_model import Ridge
from sklearn.impute import SimpleImputer
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

X = df.drop(columns=["income"])
y = df["income"]

X = X.fillna(X.median())
y = y.fillna(y.median())

ridge = Ridge(alpha=0.1)

ridge.fit(X, y)

coefficient = pd.DataFrame({
    "Features": X.columns,
    "Coefficient": ridge.coef_
})

display(coefficient)

             Features  Coefficient
0                 age  1130.880678
1    experience_years  2824.851457
2     education_years  1089.436157
3      hours_per_week   -35.371807
4   performance_score   114.930210
5  projects_completed   256.691608
6    job_satisfaction   -37.713513