In [3]:
import pandas as pd 

df = pd.read_csv("outliers_imputation_practice.xls")

In [5]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imputer = IterativeImputer(
    max_iter=10,
    random_state=45
)

df_mice = pd.DataFrame(
    imputer.fit_transform(df),
    columns=df.columns
)

df_mice.head()

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction
0,56.0,34.000000,16.0,192108.58,33.0,100.000000,29.000000,7.100000
1,46.0,19.000000,12.0,115700.97,32.2,93.180000,17.000000,6.772306
2,32.0,14.000000,16.0,118094.75,37.9,89.850000,13.000000,7.520000
3,60.0,37.000000,14.0,207761.74,49.3,100.000000,31.951864,5.510000
4,25.0,2.477007,16.0,53154.85,31.4,77.662431,0.000000,10.000000

In [6]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=4)

df_knn = df.copy()

df_result = pd.DataFrame(
    imputer.fit_transform(df_knn),
    columns=df_knn.columns
)

df_result.head()

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction
0,56.0,34.00,16.0,192108.58,33.0,100.0000,29.0,7.10
1,46.0,19.00,12.0,115700.97,32.2,93.1800,17.0,5.82
2,32.0,14.00,16.0,118094.75,37.9,89.8500,13.0,7.52
3,60.0,37.00,14.0,207761.74,49.3,100.0000,29.5,5.51
4,25.0,1.75,16.0,53154.85,31.4,77.2425,0.0,10.00

In [7]:
from sklearn.impute import SimpleImputer

df_meadian = df.copy()

imputer = SimpleImputer(strategy="median")

df_meadian[["income"]] = imputer.fit_transform(df_meadian[["income"]])

df_meadian.head()

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction
0,56.0,34.0,16.0,192108.58,33.0,100.00,29.0,7.10
1,46.0,19.0,12.0,115700.97,32.2,93.18,17.0,NaN
2,32.0,14.0,16.0,118094.75,37.9,89.85,13.0,7.52
3,60.0,37.0,14.0,207761.74,49.3,100.00,NaN,5.51
4,25.0,NaN,16.0,53154.85,31.4,NaN,0.0,10.00

In [8]:
from sklearn.impute import SimpleImputer

df_mean = df.copy()

imputer = SimpleImputer(strategy="mean")

df_mean[["income"]] = imputer.fit_transform(df_mean[["income"]])

df_mean.head(10)

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction
0,56.0,34.0,16.0,192108.58,33.0,100.00,29.0,7.10
1,46.0,19.0,12.0,115700.97,32.2,93.18,17.0,NaN
2,32.0,14.0,16.0,118094.75,37.9,89.85,13.0,7.52
3,60.0,37.0,14.0,207761.74,49.3,100.00,NaN,5.51
4,25.0,NaN,16.0,53154.85,31.4,NaN,0.0,10.00
5,38.0,17.0,12.0,96061.38,22.2,96.75,20.0,7.09
6,56.0,31.0,16.0,192654.18,38.8,100.00,27.0,6.58
7,36.0,15.0,16.0,101907.42,45.9,NaN,15.0,8.25
8,40.0,15.0,12.0,107699.33,50.4,100.00,14.0,7.17
9,28.0,3.0,12.0,55873.77,38.8,54.52,3.0,7.40

In [9]:
import pandas as pd

df = pd.DataFrame({
    "hours_studied": [1, 2, 3, 4, 5],
    "sleep_hours": [8, 7, 7, 6, 6],
    "exam_score": [40, 50, 65, 75, 90]
})

correlation = df.corr()

print(correlation)

               hours_studied  sleep_hours  exam_score
hours_studied       1.000000    -0.944911    0.997609
sleep_hours        -0.944911     1.000000   -0.920028
exam_score          0.997609    -0.920028    1.000000

In [10]:
import numpy as np

df = pd.DataFrame({
    "income": [10000, 20000, 50000, 100000, 500000]
})

df["log_income"] = np.log(df["income"])

print(df)

   income  log_income
0   10000    9.210340
1   20000    9.903488
2   50000   10.819778
3  100000   11.512925
4  500000   13.122363

In [11]:
import numpy as np

df = pd.DataFrame({
    "income": [10000, 20000, 50000, 100000, 500000]
})

df["log_income"] = np.log1p(df["income"])

print(df)

   income  log_income
0   10000    9.210440
1   20000    9.903538
2   50000   10.819798
3  100000   11.512935
4  500000   13.122365

In [ ]:
import numpy as np
import pandas as pd
from scipy.stats import zscore

df = pd.read_csv("outliers_imputation_practice.xls")

z_score = zscore(df["income"])

outliers = df[np.abs(z_score) > 0]

print(outliers)

Empty DataFrame
Columns: [age, experience_years, education_years, income, hours_per_week, performance_score, projects_completed, job_satisfaction]
Index: []

In [36]:
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

Q1 = df["income"].quantile(0.25)
Q3 = df["income"].quantile(0.75)

IQR = Q3 - Q1

lower_bond = Q1 - 1.5 * IQR
upper_bond = Q3 + 1.5 * IQR

outliers = df[
    (df["income"] < lower_bond) | (df["income"] > upper_bond)
]

print(outliers)

      age  experience_years  education_years         income  hours_per_week  \
56   23.0               0.0             16.0  320581.720629            43.6
274  33.0              15.0             14.0  616563.569423            39.7
497  52.0              26.0             14.0  607446.432059            38.3
549  60.0              40.0             12.0  879799.754078             NaN
588  45.0              20.0             12.0  374304.045526             NaN
644  50.0              31.0             16.0  776249.019685            42.1

     performance_score  projects_completed  job_satisfaction
56               59.73                 2.0              8.10
274              83.51                12.0              5.24
497             100.00                23.0              8.94
549             100.00                34.0              8.82
588              89.41                18.0              4.87
644             100.00                29.0              4.90

In [5]:
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

#There is no categories in the data set so did this
df["experience_level"] = pd.cut(
    df["experience_years"],
    bins=[0, 5, 15, 100],
    labels=["Junior", "Mid", "Senior"]
)

#This is the part of One-Hot Encoding
df_enoded = pd.get_dummies(
    df,
    columns=["experience_level"],
    dtype=int
)

df_enoded.head()

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction,experience_level_Junior,experience_level_Mid,experience_level_Senior
0,56.0,34.0,16.0,192108.58,33.0,100.00,29.0,7.10,0,0,1
1,46.0,19.0,12.0,115700.97,32.2,93.18,17.0,NaN,0,0,1
2,32.0,14.0,16.0,118094.75,37.9,89.85,13.0,7.52,0,1,0
3,60.0,37.0,14.0,207761.74,49.3,100.00,NaN,5.51,0,0,1
4,25.0,NaN,16.0,53154.85,31.4,NaN,0.0,10.00,0,0,0

In [23]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("outliers_imputation_practice.xls")

#There is no categories in the data set so did this
df["experience_level"] = pd.cut(
    df["experience_years"],
    bins=[0, 5, 15, 100],
    labels=["Junior", "Mid", "Senior"]
)

encode = LabelEncoder()

df["experience"] = encode.fit_transform(df["experience_level"])

df.head()

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction,experience_level,experience
0,56.0,34.0,16.0,192108.58,33.0,100.00,29.0,7.10,Senior,2
1,46.0,19.0,12.0,115700.97,32.2,93.18,17.0,NaN,Senior,2
2,32.0,14.0,16.0,118094.75,37.9,89.85,13.0,7.52,Mid,1
3,60.0,37.0,14.0,207761.74,49.3,100.00,NaN,5.51,Senior,2
4,25.0,NaN,16.0,53154.85,31.4,NaN,0.0,10.00,NaN,3

In [27]:
from sklearn.preprocessing import LabelEncoder, PolynomialFeatures
from sklearn.impute import KNNImputer
import pandas as pd
import numpy as np

df = pd.read_csv("outliers_imputation_practice.xls")

df["experience_level"] = pd.cut(
    df["experience_years"],
    bins=[0, 5, 15, 100],
    labels=["Junior", "Mid", "Senior"]
)

df["log_income"] = np.log1p(df["income"])

df["project_per_hour"] = df["projects_completed"] / df["hours_per_week"].replace(0, pd.NA)

imputer = KNNImputer(n_neighbors=3)

poly = PolynomialFeatures(degree=2, include_bias=False)

incoder = LabelEncoder()

df["experience_years"] = imputer.fit_transform(df[["experience_years"]])

df_poly = pd.DataFrame(
    poly.fit_transform(df[["experience_years"]]),
    columns=["experience_years", "experience_years^2"]
    )

df_enoded = pd.get_dummies(
    df,
    columns=["experience_level"],
    dtype=int
)

df["experience_level_encoded"] = incoder.fit_transform(df["experience_level"])

display(df.head())

display(df_poly.head())

display(df_enoded.head())

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction,experience_level,log_income,project_per_hour,experience_level_encoded
0,56.0,34.000000,16.0,192108.58,33.0,100.00,29.0,7.10,Senior,12.165821,0.878788,2
1,46.0,19.000000,12.0,115700.97,32.2,93.18,17.0,NaN,Senior,11.658773,0.527950,2
2,32.0,14.000000,16.0,118094.75,37.9,89.85,13.0,7.52,Mid,11.679251,0.343008,1
3,60.0,37.000000,14.0,207761.74,49.3,100.00,NaN,5.51,Senior,12.244152,NaN,2
4,25.0,16.869474,16.0,53154.85,31.4,NaN,0.0,10.00,NaN,10.880983,0.000000,3

   experience_years  experience_years^2
0         34.000000         1156.000000
1         19.000000          361.000000
2         14.000000          196.000000
3         37.000000         1369.000000
4         16.869474          284.579142

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction,log_income,project_per_hour,experience_level_Junior,experience_level_Mid,experience_level_Senior
0,56.0,34.000000,16.0,192108.58,33.0,100.00,29.0,7.10,12.165821,0.878788,0,0,1
1,46.0,19.000000,12.0,115700.97,32.2,93.18,17.0,NaN,11.658773,0.527950,0,0,1
2,32.0,14.000000,16.0,118094.75,37.9,89.85,13.0,7.52,11.679251,0.343008,0,1,0
3,60.0,37.000000,14.0,207761.74,49.3,100.00,NaN,5.51,12.244152,NaN,0,0,1
4,25.0,16.869474,16.0,53154.85,31.4,NaN,0.0,10.00,10.880983,0.000000,0,0,0

In [41]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer, KNNImputer
from sklearn.preprocessing import MinMaxScaler, StandardScaler, PolynomialFeatures, LabelEncoder, RobustScaler
from scipy.stats import zscore
import pandas as pd 
import numpy as np

df = pd.read_csv("outliers_imputation_practice.xls")

kimputer = KNNImputer(n_neighbors=3)
mimputer = IterativeImputer(max_iter=10, random_state=53)
simputer = SimpleImputer(strategy="mean")
poly = PolynomialFeatures(degree=2, include_bias=False)

df = pd.read_csv("outliers_imputation_practice.xls")

print("Imputation")

df_kimputed = pd.DataFrame(
    kimputer.fit_transform(df),
    columns=df.columns
)

df_mimputed = pd.DataFrame(
    mimputer.fit_transform(df),
    columns=df.columns
)

df_simputed = pd.DataFrame(
    simputer.fit_transform(df),
    columns=df.columns
)

display(df_kimputed.head())
display(df_mimputed.head())
display(df_simputed.head())

print("Normalization")

mscaler = MinMaxScaler()
zscaler = StandardScaler()
rscaler = RobustScaler()

df_mscaled = pd.DataFrame(
    mscaler.fit_transform(df),
    columns=df.columns
)

df_zscaled = pd.DataFrame(
    zscaler.fit_transform(df),
    columns=df.columns
)

df_rscaled = pd.DataFrame(
    rscaler.fit_transform(df),
    columns=df.columns
)

print("Transformation")

df_poly = pd.DataFrame(
    poly.fit_transform(df_mimputed[["experience_years"]]),
    columns=["experience_years", "experience_years ^ 2"]
)

display(df_poly)

display(df_mscaled.head())
display(df_zscaled.head())
display(df_rscaled.head())

Imputation

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction
0,56.0,34.000000,16.0,192108.58,33.0,100.000000,29.000000,7.100000
1,46.0,19.000000,12.0,115700.97,32.2,93.180000,17.000000,6.163333
2,32.0,14.000000,16.0,118094.75,37.9,89.850000,13.000000,7.520000
3,60.0,37.000000,14.0,207761.74,49.3,100.000000,29.666667,5.510000
4,25.0,0.333333,16.0,53154.85,31.4,76.136667,0.000000,10.000000

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction
0,56.0,34.000000,16.0,192108.58,33.0,100.000000,29.000000,7.100000
1,46.0,19.000000,12.0,115700.97,32.2,93.180000,17.000000,6.772306
2,32.0,14.000000,16.0,118094.75,37.9,89.850000,13.000000,7.520000
3,60.0,37.000000,14.0,207761.74,49.3,100.000000,31.951864,5.510000
4,25.0,2.477007,16.0,53154.85,31.4,77.662431,0.000000,10.000000

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction
0,56.0,34.000000,16.0,192108.58,33.0,100.000000,29.000000,7.100000
1,46.0,19.000000,12.0,115700.97,32.2,93.180000,17.000000,6.766396
2,32.0,14.000000,16.0,118094.75,37.9,89.850000,13.000000,7.520000
3,60.0,37.000000,14.0,207761.74,49.3,100.000000,15.922581,5.510000
4,25.0,16.869474,16.0,53154.85,31.4,87.280866,0.000000,10.000000

Normalization
Transformation

     experience_years  experience_years ^ 2
0           34.000000           1156.000000
1           19.000000            361.000000
2           14.000000            196.000000
3           37.000000           1369.000000
4            2.477007              6.135564
..                ...                   ...
995         31.000000            961.000000
996          0.000000              0.000000
997         17.054618            290.859981
998          0.000000              0.000000
999          3.000000              9.000000

[1000 rows x 2 columns]

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction
0,0.904762,0.850,0.75,0.202808,0.130008,1.000000,0.180124,0.601100
1,0.666667,0.475,0.25,0.114234,0.120964,0.922613,0.105590,NaN
2,0.333333,0.350,0.75,0.117009,0.185403,0.884827,0.080745,0.658872
3,1.000000,0.925,0.50,0.220954,0.314280,1.000000,NaN,0.382393
4,0.166667,NaN,0.75,0.041729,0.111920,NaN,0.000000,1.000000

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction
0,1.367945,1.436700,0.673173,0.993906,-1.075163,0.882582,1.202142,0.219877
1,0.558362,0.178683,-1.258804,-0.113911,-1.168017,0.409342,0.099042,NaN
2,-0.575054,-0.240657,0.673173,-0.079204,-0.506435,0.178272,-0.268658,0.496697
3,1.691778,1.688304,-0.292815,1.220858,0.816729,0.882582,NaN,-0.828085
4,-1.141762,NaN,0.673173,-1.020754,-1.260870,NaN,-1.463684,2.131254

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction
0,0.727273,0.809524,0.0,0.745157,-0.919192,0.381437,0.8125,0.163823
1,0.272727,0.095238,-2.0,-0.065218,-1.000000,0.063417,0.0625,NaN
2,-0.363636,-0.142857,0.0,-0.039830,-0.424242,-0.091862,-0.1875,0.354949
3,0.909091,0.952381,-1.0,0.911174,0.727273,0.381437,NaN,-0.559727
4,-0.681818,NaN,0.0,-0.728580,-1.080808,NaN,-1.0000,1.483504

In [50]:
from sklearn.feature_selection import VarianceThreshold
from sklearn.impute import KNNImputer
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

correlation = df.corr(numeric_only=True)

display(correlation)

correlation = df.corr(numeric_only=True)["income"].sort_values(ascending=False)

display(correlation)

imputer = KNNImputer(n_neighbors=4)

df_imputed = pd.DataFrame(
    imputer.fit_transform(df),
    columns=df.columns
)

selector = VarianceThreshold(threshold=3)

selector.fit(df_imputed)

selected = df_imputed.columns[selector.get_support()]

print(selected)

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction
age,1.000000,0.971990,0.070049,0.777266,-0.012017,0.680879,0.844886,-0.037613
experience_years,0.971990,1.000000,0.064277,0.802388,-0.026298,0.688882,0.867740,-0.053385
education_years,0.070049,0.064277,1.000000,0.091330,0.014710,0.200615,0.070565,-0.004700
income,0.777266,0.802388,0.091330,1.000000,-0.023975,0.553712,0.680860,-0.040896
hours_per_week,-0.012017,-0.026298,0.014710,-0.023975,1.000000,-0.054891,-0.018764,-0.011210
performance_score,0.680879,0.688882,0.200615,0.553712,-0.054891,1.000000,0.588752,-0.039823
projects_completed,0.844886,0.867740,0.070565,0.680860,-0.018764,0.588752,1.000000,-0.087502
job_satisfaction,-0.037613,-0.053385,-0.004700,-0.040896,-0.011210,-0.039823,-0.087502,1.000000

income                1.000000
experience_years      0.802388
age                   0.777266
projects_completed    0.680860
performance_score     0.553712
education_years       0.091330
hours_per_week       -0.023975
job_satisfaction     -0.040896
Name: income, dtype: float64

Index(['age', 'experience_years', 'education_years', 'income',
       'hours_per_week', 'performance_score', 'projects_completed'],
      dtype='str')

In [49]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

X = df.drop(columns=["income"])
y = df["income"]

X = X.fillna(X.median())
y = y.fillna(y.median())

model = LinearRegression()

rfe = RFE(estimator=model, n_features_to_select=3)

rfe.fit(X, y)

selected = X.columns[rfe.support_]

print(selected)

Index(['age', 'experience_years', 'education_years'], dtype='str')

In [53]:
from sklearn.linear_model import Lasso

X = df_imputed.drop(columns=["income"])
y = df_imputed["income"]

lasso = Lasso(alpha=0.2)

lasso.fit(X, y)

coeffients = pd.DataFrame({
    "Feature": X.columns,
    "Coeffients": lasso.coef_
})

display(coeffients)

selected = coeffients[coeffients["Coeffients"] != 0]

display(selected)

              Feature   Coeffients
0                 age  -436.328854
1    experience_years  5231.368959
2     education_years  1585.410496
3      hours_per_week  -100.312587
4   performance_score   -43.491865
5  projects_completed   -73.162616
6    job_satisfaction   199.052671

              Feature   Coeffients
0                 age  -436.328854
1    experience_years  5231.368959
2     education_years  1585.410496
3      hours_per_week  -100.312587
4   performance_score   -43.491865
5  projects_completed   -73.162616
6    job_satisfaction   199.052671

In [55]:
from sklearn.linear_model import Ridge

ridge = Ridge(alpha=0.1)

ridge.fit(X, y)

coeffients = pd.DataFrame({
    "Feature" : X.columns,
    "Coeffients" : ridge.coef_
})

display(coeffients)

              Feature   Coeffients
0                 age  -436.311463
1    experience_years  5231.346852
2     education_years  1585.420567
3      hours_per_week  -100.315723
4   performance_score   -43.491659
5  projects_completed   -73.159186
6    job_satisfaction   199.134371

In [56]:

df = pd.read_csv("outliers_imputation_practice.xls")

df["experience"] = pd.cut(
    df["experience_years"],
    bins=[0, 5, 15, 100],
    labels=["Junior", "Mid", "Sinior"]
)

df_encoded = pd.get_dummies(
    df,
    columns=["experience"],
    dtype=int
)

display(df_enoded)

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction,log_income,project_per_hour,experience_level_Junior,experience_level_Mid,experience_level_Senior
0,56.0,34.000000,16.0,192108.58,33.0,100.00,29.0,7.10,12.165821,0.878788,0,0,1
1,46.0,19.000000,12.0,115700.97,32.2,93.18,17.0,NaN,11.658773,0.527950,0,0,1
2,32.0,14.000000,16.0,118094.75,37.9,89.85,13.0,7.52,11.679251,0.343008,0,1,0
3,60.0,37.000000,14.0,207761.74,49.3,100.00,NaN,5.51,12.244152,NaN,0,0,1
4,25.0,16.869474,16.0,53154.85,31.4,NaN,0.0,10.00,10.880983,0.000000,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,50.0,31.000000,16.0,170826.96,37.6,100.00,24.0,8.83,12.048412,0.638298,0,0,1
996,21.0,0.000000,12.0,50426.91,38.6,59.19,4.0,8.82,10.828300,0.103627,0,0,0
997,39.0,16.869474,12.0,120388.75,46.4,89.10,16.0,8.97,11.698490,0.344828,0,0,0
998,19.0,0.000000,14.0,42263.64,42.2,90.18,2.0,7.24,10.651706,0.047393,0,0,0
999,27.0,3.000000,14.0,69957.97,32.2,NaN,5.0,NaN,11.155664,0.155280,1,0,0

In [ ]:
from sklearn.preprocessing import LabelEncoder

enocer = LabelEncoder()

df["experience_level"] = pd.cut(
    df["experience_years"],
    bins=[0, 5, 15, 100],
    labels=["Junior", "Mid", "Sinior"]
)

df["experience"] = enocer.fit_transform(df["experience_level"])

display(df)

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction,experience,experience_level
0,56.0,34.0,16.0,192108.58,33.0,100.00,29.0,7.10,2,Sinior
1,46.0,19.0,12.0,115700.97,32.2,93.18,17.0,NaN,2,Sinior
2,32.0,14.0,16.0,118094.75,37.9,89.85,13.0,7.52,1,Mid
3,60.0,37.0,14.0,207761.74,49.3,100.00,NaN,5.51,2,Sinior
4,25.0,NaN,16.0,53154.85,31.4,NaN,0.0,10.00,3,NaN
...,...,...,...,...,...,...,...,...,...,...
995,50.0,31.0,16.0,170826.96,37.6,100.00,24.0,8.83,2,Sinior
996,21.0,0.0,12.0,50426.91,38.6,59.19,4.0,8.82,3,NaN
997,39.0,NaN,12.0,120388.75,46.4,89.10,16.0,8.97,3,NaN
998,19.0,0.0,14.0,42263.64,42.2,90.18,2.0,7.24,3,NaN
999,27.0,3.0,14.0,69957.97,32.2,NaN,5.0,NaN,0,Junior

: