In [6]:
import pandas as pd

df = pd.read_csv("outliers_imputation_practice.xls")

df.fillna(df.median())

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction
0,56.0,34.0,16.0,192108.58,33.0,100.00,29.0,7.10
1,46.0,19.0,12.0,115700.97,32.2,93.18,17.0,6.74
2,32.0,14.0,16.0,118094.75,37.9,89.85,13.0,7.52
3,60.0,37.0,14.0,207761.74,49.3,100.00,16.0,5.51
4,25.0,17.0,16.0,53154.85,31.4,91.82,0.0,10.00
...,...,...,...,...,...,...,...,...
995,50.0,31.0,16.0,170826.96,37.6,100.00,24.0,8.83
996,21.0,0.0,12.0,50426.91,38.6,59.19,4.0,8.82
997,39.0,17.0,12.0,120388.75,46.4,89.10,16.0,8.97
998,19.0,0.0,14.0,42263.64,42.2,90.18,2.0,7.24
999,27.0,3.0,14.0,69957.97,32.2,91.82,5.0,6.74

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df_scaled = pd.DataFrame(
    scaler.fit_transform(df),
    columns=df.columns
)

display(df_scaled)

,age,experience_years,education_years,income,hours_per_week,performance_score,projects_completed,job_satisfaction
0,0.904762,0.850,0.75,0.202808,0.130008,1.000000,0.180124,0.601100
1,0.666667,0.475,0.25,0.114234,0.120964,0.922613,0.105590,NaN
2,0.333333,0.350,0.75,0.117009,0.185403,0.884827,0.080745,0.658872
3,1.000000,0.925,0.50,0.220954,0.314280,1.000000,NaN,0.382393
4,0.166667,NaN,0.75,0.041729,0.111920,NaN,0.000000,1.000000
...,...,...,...,...,...,...,...,...
995,0.761905,0.775,0.75,0.178138,0.182011,1.000000,0.149068,0.839065
996,0.071429,0.000,0.25,0.038566,0.193316,0.536925,0.024845,0.837689
997,0.500000,NaN,0.25,0.119668,0.281496,0.876317,0.099379,0.858322
998,0.023810,0.000,0.50,0.029103,0.234014,0.888572,0.012422,0.620358
999,0.214286,0.075,0.50,0.061207,0.120964,NaN,0.031056,NaN

: